[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.19.0"
  NPM_VERSION = "11.3.0"
  NEXT_TELEMETRY_DISABLED = "1"

# Règles spécifiques pour Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuration du serveur de développement
[dev]
  command = "npm run dev"
  port = 8000
  targetPort = 3000
  framework = "nextjs"